# Use coolstore-mono as the base
FROM jbossdemocentral/brms-coolstore-base:latest

# Maintainer details
MAINTAINER Greg Hoelzer with Original Contributors Andrew Block, Eric D. Schabell, Duncan Doylle, Jaen Swart

# Environment Variables
#ENV BRMS_HOME /opt/jboss/brms/jboss-eap-7.0
#ENV BRMS_VERSION_MAJOR 6
#ENV BRMS_VERSION_MINOR 4
#ENV BRMS_VERSION_MICRO 0
#ENV BRMS_VERSION_PATCH GA

#ENV EAP_VERSION_MAJOR 7
#ENV EAP_VERSION_MINOR 0
#ENV EAP_VERSION_MICRO 0

# Clone the brms-coolstore-repo repository
USER root
RUN git clone --bare https://github.com/jbossdemocentral/brms-coolstore-repo.git $BRMS_HOME/bin/.niogit/coolstore-demo.git

COPY projects /opt/jboss/brms-projects
COPY support/libs /opt/jboss/brms-projects/libs
COPY support/userinfo.properties $BRMS_HOME/standalone/deployments/business-central.war/WEB-INF/classes/
COPY support/standalone.xml $BRMS_HOME/standalone/configuration/
COPY support/settings.xml $BRMS_HOME/bin/.settings.xml

# Run Demo Maven build and cleanup
RUN mvn install:install-file -Dfile=/opt/jboss/brms-projects/libs/coolstore-2.0.0.jar -DgroupId=com.redhat -DartifactId=coolstore -Dversion=2.0.0 -Dpackaging=jar \
  && mvn clean install -f /opt/jboss/brms-projects/brms-coolstore-demo/pom.xml \
  && cp /opt/jboss/brms-projects/brms-coolstore-demo/target/brms-coolstore-demo.war $BRMS_HOME/standalone/deployments/ \
  && rm -rf ~/.m2/repository /opt/jboss/brms-projects
# Don't think we need this
#  && chown -R jboss:jboss $BRMS_HOME/bin/.niogit $BRMS_HOME/standalone/configuration/application-roles.properties $BRMS_HOME/standalone/configuration/standalone.xml $BRMS_HOME/standalone/deployments/brms-coolstore-demo.war $BRMS_HOME/standalone/deployments/business-central.war/WEB-INF/classes/userinfo.properties \
#  && rm -rf ~/.m2/repository /opt/jboss/brms-projects

# Update to use OCP Restricted SCC
RUN chgrp -R 0 /opt/jboss
RUN chmod -R g+rw /opt/jboss
RUN find /opt/jboss -type d -exec chmod g+x {} +

USER 1000
