apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: brms-coolstore-demo
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    name: brms-coolstore-demo
  spec:
    host: 
    path: /brms-coolstore-demo/
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: brms-coolstore-demo
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: brms-coolstore-demo
    name: brms-coolstore-demo
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 9990-tcp
      port: 9990
      protocol: TCP
      targetPort: 9990
    - name: 9999-tcp
      port: 9999
      protocol: TCP
      targetPort: 9999
    selector:
      deploymentconfig: brms-coolstore-demo
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: brms-coolstore-app
    name: brms-coolstore-app
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: DockerImage
        name: >-
          docker-registry.default.svc:5000/coolstore-mono/brms-coolstore-demo:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /support/docker-OCP-app
      git:
        uri: https://github.com/mono2micro/coolstore-mono.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: brms-coolstore-base:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: h3b_6MLF7MlXra8YCplG
      type: GitHub
    - generic:
        secret: XPjyO6uEPnJrUAWuLg1K
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "brms-coolstore-demo", "namespace":
        "", "kind": "DeploymentConfig"}]'
    creationTimestamp: null
    labels:
      name: coolstore-mono-mvn-pipeline
    name: coolstore-mon-mvn-pipeline
  spec:
    nodeSelector: null
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |
          try {
             timeout(time: 20, unit: 'MINUTES') {
                def appName="brms-coolstore-demo"
                def project=""

                node {
                  stage("Initialize") {
                    project = "brms-coolstore-demo"
                  }
                }

                node {

                  stage("Build Coolstore Monolith Application Image") {
                    // *** Uncomment for 1st Run *** if Lab 1 was skipped
                    // sh "mvn clean fabric8:deploy -Popenshift --file lab/pom.xml"
                    //sh "mvn clean package -Popenshift --file lab/pom.xml"
                    //stash name:"jar", includes:"lab/target/product-catalog.jar"
                    sh "echo '***** Starting docker App Build Here *****'"
                    openshiftBuild apiURL: '', authToken: '', bldCfg: 'brms-coolstore-app', buildName: '', checkForTriggeredDeployments: 'false', commitID: '', namespace: '', showBuildLogs: 'false', verbose: 'false', waitTime: '', waitUnit: 'sec'
                  }
                }

                node {
                  stage("Deploy Coolstore Image") {
                    openshiftDeploy deploymentConfig: "brms-coolstore-demo"
                  }
                  stage("Smoke Test Coolstore") {
                    sh 'curl http://brms-coolstore-demo-coolstore-mono.apps.c7.core.rht-labs.com/brms-coolstore-demo/ | grep -i "<title>Red Hat Cool Store</title>"'
                  }
                }
             }
          } catch (err) {
              node {
                stage("Fallback to Last Release") {
                  openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'brms-coolstore-demo', destTag: 'latest', destinationAuthToken: '', destinationNamespace: '', namespace: '', srcStream: 'brms-coolstore-demo', srcTag: 'last-release', verbose: 'false'
                  openshiftDeploy deploymentConfig: "brms-coolstore-demo"
              }
              echo "in catch block"
              echo "Caught: ${err}"
              currentBuild.result = 'FAILURE'
              throw err
              }
          }
          node {
            stage("Tag and Release Image") {
              input "Promote next Release"
              openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'brms-coolstore-demo', destTag: 'next-release', destinationAuthToken: '', destinationNamespace: '', namespace: '', srcStream: 'brms-coolstore-demo', srcTag: 'latest', verbose: 'false'
            }
          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: brms-coolstore-demo
    name: brms-coolstore-demo
  spec:
    replicas: 1
    selector:
      app: brms-coolstore-demo
      deploymentconfig: brms-coolstore-demo
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: brms-coolstore-demo
          deploymentconfig: brms-coolstore-demo
      spec:
        containers:
        - image: docker-registry.default.svc:5000/coolstore-mono/brms-coolstore-demo:latest
          imagePullPolicy: Always
          name: brms-coolstore-demo
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 9990
            protocol: TCP
          - containerPort: 9999
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /brms-coolstore-demo/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
            requests:
              cpu: "1"
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        containerNames:
        - brms-coolstore-demo
        from:
          kind: ImageStreamTag
          name: brms-coolstore-demo:latest
          namespace: coolstore-mono
      type: ImageChange
